### ISSUE TITLE
Ability to get handlers back

### ISSUE THREAD

**Issue by ccoors** [acknak/ghakuf#2]
I'm not sure how to get MIDI data back from the handlers. Right now I give my handler a raw mutable pointer to a data structure. It then fills that structure with the information I need, so I can access it later. Of course, this is ```unsafe {}```, which is not nice.

It would be nice if I could get the ```Box<Handler>``` back from the Reader after running read().

**Comment by katyo** [comment]
The handler can borrow the reference to variable to place result, but the reader hold handler in a box with static life time. I think it's not so good design because the reference to result must have the same life time i.e. static.

**Comment by acknak** [comment]
Thank you for your advice!

To get MIDI data back from the handlers, please borrow the reference of data structures for MIDI data at handler.
https://github.com/acknak/ghakuf/blob/master/examples/example.rs
We can't get the `Box<Handler>` for the purpose of get data back due to type erasure of trait objects.

I agree for the advice about `Box<Handler>`'s life time, so I change trait object type from `Box<Handler>` to `&'a mut Handler` after version 0.5. Please try it!
